MODEL:
  TYPE: vit
  NAME: simmim_pretrain
  DROP_PATH_RATE: 0.1
  DROP_RATE: 0.0

  VIT:
    MLP_RATIO: 4
    QKV_BIAS: True
    INIT_VALUES: 0.1
    EMBED_DIM: 768
    PATCH_SIZE: 16
    IN_CHANS: 3
    DEPTH: 12
    NUM_HEADS: 12
    USE_APE: False
    USE_RPB: False
    USE_SHARED_RPB: True
    USE_MEAN_POOLING: False
DATA:
  IMG_SIZE: 224
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
TRAIN:
  EPOCHS: 800
  WARMUP_EPOCHS: 10
  BASE_LR: 1e-4
  WARMUP_LR: 5e-7
  WEIGHT_DECAY: 0.05
  LR_SCHEDULER:
    NAME: 'multistep'
    GAMMA: 0.1
    MULTISTEPS: [700,]
PRINT_FREQ: 100
SAVE_FREQ: 5
PRETRAINED: "/home/jackson/Desktop/Paper/pretrain_model/simmim_pretrain__vit_base__img224__800ep.pth"
TAG: simmim_pretrain__vit_base__img224__800ep